version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          name: "Specifications"
          command: |
           nproc --all
           free
           
      - run:
          name: "Cloning!"
          command: |
           git clone --depth=1 https://github.com/a3-Prjkt/kernel_xiaomi_ginkgo_consistenX kernel
           cd kernel
           
      - run:
          name: "Compiling!"
          command: |
           bash circle.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
