version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
  
  steps:
      - run:
          name: "Time Check"
          command: |
           echo ============
           echo Manila Time $(TZ=Asia/Manila date +"%Y%m%d-%H%M")
           echo ============
           echo The Main Thing Begins :)
           echo ============
       - run:
           name: "Precaution"
           command: |
            echo This a CIsX TEST build
            echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++
            echo This could be Working or not
            echo but still don't be confident it
            echo cause it could be unstable sometimes
            echo ========================================================
            echo Thanks for your understanding
            echo Report Bugs on the telegram Group @A3_Project_Discussion
      - run:
          name: "Specifications"
          command: |
           echo Core Count
           echo ===================
           nproc --all
           echo ===================
           echo 
           echo RAM/Swap Free
           echo ===================
           free -h
           echo ===================
           echo
           echo Storage
           echo ===================
           df -h -x squashfs --total
           echo ===================
           
      - run:
          name: "Cloning!"
          command: |
           git clone --depth=1 https://github.com/a3-Prjkt/kernel_xiaomi_ginkgo_consistenX -b eleven-test kernel
           git status
           
      - run:
          name: "Compiling!"
          command: |
           cd kernel
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
