version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          name: "Specifications"
          command: |
           echo Core Count
           echo ========
           nproc --all
           echo ========
           echo RAM/Swap Free
           echo ==============
           free -h
           echo ==============
           echo Storage
           echo ===================
           df -h -x squashfs --total
           echo ===================
           
      - run:
          name: "Cloning!"
          command: |
           git clone --depth=1 https://github.com/a3-Prjkt/kernel_xiaomi_ginkgo_consistenX -b eleven-test kernel
           
      - run:
          name: "Compiling!"
          command: |
           cd kernel
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
