version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/a3-Prjkt/kernel_xiaomi_ginkgo_consistenX kernel
           bash script/.circleci/kernel/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
